# Generated by Django 4.1.7 on 2023-04-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0063_user_kyc_dima'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kyc_frama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frama_Aadhar_card_no', models.IntegerField()),
                ('frama_Pan_card_no', models.CharField(max_length=50)),
                ('frama_Bank_Name', models.CharField(max_length=200)),
                ('frama_Bank_account_number', models.IntegerField()),
                ('frama_user_IFSC_code', models.CharField(max_length=200)),
                ('frama_Bank_account_holder_name', models.CharField(max_length=200)),
                ('frama_gst_no', models.CharField(max_length=50)),
                ('frama_company_incorp_img', models.FileField(upload_to='frama incorporation')),
                ('frama_profile_verification_video', models.FileField(upload_to='frama profile verification')),
                ('frama_Aadhar_back_img', models.ImageField(blank=True, null=True, upload_to='frama Adharcard back image/')),
                ('frama_Aaadhar_front_img', models.ImageField(blank=True, null=True, upload_to='frama Adharcard front image/')),
                ('frama_Pan_card_img', models.ImageField(blank=True, null=True, upload_to='frama Pancard image/')),
                ('frama_user_id_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.profile')),
            ],
        ),
    ]
