# Generated by Django 4.1.7 on 2023-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_digitalmarketingrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='alltransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Currency', models.CharField(max_length=150)),
                ('fromsource', models.CharField(max_length=150)),
                ('to', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=150)),
                ('transactionid', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('Status', models.CharField(max_length=150)),
            ],
        ),
    ]
