# Generated by Django 4.1.7 on 2023-03-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alltransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('refrence_id', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=150)),
            ],
        ),
    ]
