# Generated by Django 4.1.7 on 2023-03-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_masteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteruser',
            old_name='refrence_id',
            new_name='r_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refrence_id',
        ),
        migrations.AddField(
            model_name='user',
            name='refrence_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refrence_id', to='apps.masteruser'),
            preserve_default=False,
        ),
    ]
