# Generated by Django 4.1.7 on 2023-03-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_refrence_id_masteruser_r_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refrence_user_id',
        ),
        migrations.DeleteModel(
            name='masteruser',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
