# Generated by Django 4.1.7 on 2023-03-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_masteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alltransactions',
        ),
        migrations.DeleteModel(
            name='Digitalmarketingrevenue',
        ),
        migrations.DeleteModel(
            name='masteruser',
        ),
        migrations.DeleteModel(
            name='revenue',
        ),
    ]
