# Generated by Django 4.1.7 on 2023-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password_2',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
