# Generated by Django 4.1.7 on 2023-03-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
