# Generated by Django 4.1.7 on 2023-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('designation', models.CharField(max_length=50, null=True)),
                ('residence_state', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.IntegerField(max_length=10, null=True)),
                ('Email_id', models.EmailField(max_length=254, null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('Website_link', models.URLField(null=True)),
            ],
        ),
    ]
