# Generated by Django 4.1.7 on 2023-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_profile_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_Details',
        ),
        migrations.AddField(
            model_name='profile',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Website_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
