# Generated by Django 4.1.7 on 2023-04-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_profile_skills_profile_skill1_profile_skill2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill5',
        ),
    ]
