# Generated by Django 4.1.7 on 2023-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_profile_skill2_remove_profile_skill3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
