# Generated by Django 4.1.7 on 2023-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_profile_details_remove_profile_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile_details',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile_details',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
