# Generated by Django 4.1.7 on 2023-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_delete_profile_details_profile_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Website_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='residence_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill5',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
