# Generated by Django 4.1.7 on 2023-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_profile_email_id_profile_website_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
