# Generated by Django 4.1.7 on 2023-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
