# Generated by Django 4.1.7 on 2023-04-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_profile_profile_img_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Website_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='residence_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill5',
        ),
    ]
