# Generated by Django 4.1.7 on 2023-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_user_kyc_dima_delete_formentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_kyc_dima',
            name='Aaadhar_front_img',
        ),
        migrations.RemoveField(
            model_name='user_kyc_dima',
            name='Aadhar_back_img',
        ),
        migrations.RemoveField(
            model_name='user_kyc_dima',
            name='Pan_card_img',
        ),
    ]
