# Generated by Django 4.1.7 on 2023-04-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_remove_user_kyc_dima_aaadhar_front_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
