# Generated by Django 4.1.7 on 2023-04-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_delete_user_kyc_dima'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kyc_dima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_card_no', models.IntegerField(max_length=12)),
                ('Aaadhar_front_img', models.ImageField(blank=True, null=True, upload_to='Adharcard front image/')),
                ('Aadhar_back_img', models.ImageField(blank=True, null=True, upload_to='Adharcard back image/')),
                ('Pan_card_no', models.CharField(max_length=13)),
                ('Pan_card_img', models.ImageField(blank=True, null=True, upload_to='Pancard image/')),
                ('Bank_Name', models.CharField(max_length=50)),
                ('Bank_account_number', models.IntegerField(max_length=15)),
                ('user_IFSC_code', models.CharField(max_length=11)),
                ('Bank_account_holder_name', models.CharField(max_length=50)),
                ('profile_verification_video', models.FileField(upload_to='Profile Verification video')),
                ('used_id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profile')),
            ],
        ),
    ]
