# Generated by Django 4.1.7 on 2023-04-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_remove_user_kyc_dima_bank_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
