# Generated by Django 4.1.7 on 2023-04-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_user_kyc_dima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kyc_dima',
            name='user_id_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.profile'),
        ),
    ]
