# Generated by Django 4.1.7 on 2023-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_alter_user_kyc_dima_user_id_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
