# Generated by Django 4.1.7 on 2023-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_user_kyc_dima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kyc_dima',
            name='Pan_card_no',
            field=models.IntegerField(),
        ),
    ]
