# Generated by Django 4.1.7 on 2023-04-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0053_alter_user_kyc_dima_pan_card_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
