# Generated by Django 4.1.7 on 2023-04-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0059_user_kyc_dima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
