# Generated by Django 4.1.7 on 2023-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0063_user_kyc_dima'),
    ]

    operations = [
        migrations.CreateModel(
            name='dima_documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
