# Generated by Django 4.1.7 on 2023-04-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0068_dima_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dima_documents',
        ),
    ]
