# Generated by Django 4.1.7 on 2023-04-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0069_delete_dima_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
