# Generated by Django 4.1.7 on 2023-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0071_user_kyc_dima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_kyc_dima',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_kyc_dima',
            name='user_id_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
