# Generated by Django 4.1.7 on 2023-04-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0072_remove_user_kyc_dima_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_dima',
        ),
    ]
