# Generated by Django 4.1.7 on 2023-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0075_delete_user_kyc_dima'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kyc_dima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_no', models.CharField(max_length=50)),
                ('Aadhar_card_no', models.IntegerField()),
                ('Pan_card_no', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=200)),
                ('Bank_account_number', models.IntegerField()),
                ('user_IFSC_code', models.CharField(max_length=200)),
                ('Bank_account_holder_name', models.CharField(max_length=200)),
                ('profile_verification_video', models.FileField(upload_to='Profile Verification video')),
                ('Aadhar_back_img', models.ImageField(blank=True, null=True, upload_to='Adharcard back image/')),
                ('Aaadhar_front_img', models.ImageField(blank=True, null=True, upload_to='Adharcard front image/')),
                ('Pan_card_img', models.ImageField(blank=True, null=True, upload_to='Pancard image/')),
            ],
        ),
    ]
