# Generated by Django 4.1.7 on 2023-04-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_profile_clima_email_id_profile_clima_website_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_clima',
            old_name='user',
            new_name='user_id',
        ),
    ]
