# Generated by Django 4.1.7 on 2023-04-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Aaadhar_front_img',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Aadhar_back_img',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Bank_Name',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Bank_account_holder_name',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Bank_account_number',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Pan_card_img',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_Pan_card_no',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_profile_verification_video',
        ),
        migrations.RemoveField(
            model_name='user_kyc_clima',
            name='clima_user_IFSC_code',
        ),
    ]
