# Generated by Django 4.1.7 on 2023-04-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_remove_user_kyc_clima_clima_aaadhar_front_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_clima',
        ),
    ]
