# Generated by Django 4.1.7 on 2023-04-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_clima',
        ),
    ]
