# Generated by Django 4.1.7 on 2023-04-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_clima',
        ),
    ]
