# Generated by Django 4.1.7 on 2023-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0018_rename_user_profile_clima_user_clima'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_clima',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='Website_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile image/'),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='residence_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='skill1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='skill2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='skill3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='skill4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_clima',
            name='skill5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
