# Generated by Django 4.1.7 on 2023-04-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0019_profile_clima_email_id_profile_clima_website_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_clima',
            old_name='user_clima',
            new_name='user',
        ),
    ]
