# Generated by Django 4.1.7 on 2023-04-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0021_delete_profile_clima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_kyc_clima',
        ),
    ]
